### ISSUE TITLE
run error on osx

### ISSUE THREAD

**Issue by alexus1211** [damianxd/VeraLink#2]
Hi,

now I followed the same instructions on MACOSX Mavericks. Everything installs correctly but as soon as I run VeraLink.js I get the following error:

alextech:VeraLink Aleco$ node VeraLink.js

module.js:340
    throw err;
    ^
Error: Cannot find module './node_modules/hap-nodejs/node_modules/node-persist/node-persist.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Aleco/bin/Homebridge/VeraLink/index.js:9:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
alextech:VeraLink Aleco$ npm --version
3.3.6
alextech:VeraLink Aleco$ node --version
v0.10.31

Any hints?

**Comment by damianxd** [comment]
Sure, do a
```cd node_modules/hap-nodejs/```

```npm install```

Then try to start the app again

**Comment by alexus1211** [comment]
thanks it worked.
